const samplelisting = [
    {
        //self help book data
        seller_name:"Ujjwal",
        seller_contact:"7350293920",
        seller_city:"Amravati",
        book_name:"Atomic Habits",
        book_category:"Self-Help",
        book_price:150,
        seller_city:"Amaravi",
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSiPLr6_h2DrHdsW94LhGfWgDHDcBrUpoqdg&s",
        image2_path: "https://cdn.shopify.com/s/files/1/2616/0946/files/Atomic_Habits_Book_Underline_1024x1024.gif?v=1549726824",
        image3_path: "https://images.squarespace-cdn.com/content/v1/59aec08ae9bfdff5206a771f/1585519582639-DXKZR2223SKOTKLQBEWV/IMG_7598.JPG",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkZZimOw-rXyrjdYSf5qpoBNUY-nIsjRYFdQ&s",
        image5_path: "https://view.publitas.com/51937/1061288/pages/2b311812-9d2d-4cc6-bd20-7e066cde6de1-at1000.jpg",
    },
    {
        seller_name: "Aarav",
        seller_contact: "9876543210",
        seller_city: "Pune",
        book_name: "Deep Work",
        book_category: "Self-Help",
        book_price: 200,
        seller_city:"Nagpur",
        image1_path: "https://m.media-amazon.com/images/I/81JJ7fyyKyS.jpg",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkfFugTlr9dsfVwBhLe8Akb6hBSCcOYQjmVg&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQsc4aiRPBiZBUOVclFTnmHoE89vm_EUOzqA&s",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBtZaAmaO4Cy7u4qoE3lCdslIjiIRRFS2FAQ&s",
        image5_path: "https://m.media-amazon.com/images/I/81rKl4dNAtS._AC_UF1000,1000_QL80_.jpg"
    },
    {
        seller_name: "Neha",
        seller_contact: "9123456789",
        seller_city: "Mumbai",
        book_name: "Rich Dad Poor Dad",
        book_category: "Self-Help",
        book_price: 180,
        seller_city:"Amravati",
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE8F_CvcawPnknz08VPj_pkbGYJo7Z3L_LnA&s",
        image2_path: "https://images.meesho.com/images/products/426347971/umzam_512.webp",
        image3_path: "https://miro.medium.com/v2/resize:fit:1400/1*Ul69MX_vdCymhDIo63xpgQ.jpeg",
        image4_path: "https://m.media-amazon.com/images/I/812PssyDqzL._AC_UF1000,1000_QL80_.jpg",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSotWocWznj7GbcmZDREb90_lcswO0184diaA&s"
    },
    {
        seller_name: "Rohan",
        seller_contact: "7896541230",
        seller_city: "Delhi",
        book_name: "The Psychology of Money",
        book_category: "Self-Help",
        book_price: 220,
        seller_city:"Nagpur",
        image1_path: "https://m.media-amazon.com/images/I/81Dky+tD+pL.jpg",
        image2_path: "https://pbs.twimg.com/media/FIVpVBpVgAEWQnr.jpg:large",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_Ik4HWdRLM_0-pjDCMVzRguwoJQB3R2NzFqx3BK3YYucQXkCN0PUQFeU2XnPacTiHdxE&usqp=CAU",
        image4_path: "https://www.books2door.com/cdn/shop/products/B2D4776-ThePsychologyofMoney-inside.jpg?v=1678217798",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEviURMy4HkudBnxUW08mCnypmptU4uA72jg&s"
    },
    //Academic book data
    {
        seller_name: "Karan",
        seller_contact: 9876543211,
        seller_city: "Hyderabad",
        book_name: "Operating System Concepts",
        book_category: "Academic",
        book_price: 480,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsu5mJNk9OJzuNRYBJ5Z-MwMfgOEIXuGMt7w&s",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBM-GuS9DSGKGhSY0J7m8op4iWYw__1aHmHA&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgGTEUvo6dqViRiAH7H64D50ucbwVWypqr-az0x9FVXVIf4CLTWa2p1r071PVgGiUM6hU&usqp=CAU",
        image4_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-ZnHk1-61ohtY1X0uSM4cU4-ekFuHI46Zq5O1lx6We58QCYO6PWvv_Jgjje-a4DFbdkA&usqp=CAU",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_neJTw-Jb3eC2fgchirFPUEUjSMRcDKFL-5ipZEWdYBzSgl-1kvXz5XtNoQorUHO5Nok&usqp=CAU"
    },
    {
        seller_name:" Priya",
        seller_contact: 8765432109,
        seller_city: "Bengaluru",
        book_name: "Computer Organization and Design",
        book_category: "Academic",
        book_price: 520,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZDKnidKxoVqR_s2Wzk92PZ-lndhMS1X4Z4w&s",
        image2_path:"https://m.media-amazon.com/images/I/91fJkTnjA9L._AC_UF1000,1000_QL80_.jpg",
        image3_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1dHZzDbyEYN3Ea4a0GVDfsUKDDx5mbed0xlNddTSe5d4opOhkH-6W1EkWc9dwlNlvC1Q&usqp=CAU",
        image4_path: "https://m.media-amazon.com/images/I/81kzvCBVhlL._AC_UF350,350_QL80_.jpg",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOMVMmOXlnh0JT35YC7fwrcPrqXQoNcL4qqmQbyG2Ym3kCFxqOCd8lYOgBTgfvp_C0mfM&usqp=CAU"
    },
    {
        seller_name: "Aditya",
        seller_contact: 7654321098,
        seller_city: "Chennai",
        book_name: "Digital Logic and Computer Design",
        book_category: "Academic",
        book_price: 490,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThN0g5nLiN3prKStC_UqesLK-O1_dxrZ_qYg&s",
        image2_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-3QYpNl5Cdk-HPn4MCxyt7ymw-edB_3GODZKJszTcdN4K9bPG-YRrVf7wn4TWbX02JaM&usqp=CAU",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4YaU3z3bnJBpPwasahNBABGymCvzypIn-gg&s",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9gxn259wvmAAHHWwq3Os4P8GRF0x5EY4H2g&s",
        image5_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaAZlaFefQASZhSqQz3p4LPtwOFit69_QdCkBWqnFJW1FISS1q2z4zlmRk7dM3IeYsl0s&usqp=CAU"
    },
    {
        seller_name: "Riya",
        seller_contact: 6543210987,
        seller_city: "Kolkata",
        book_name: "Computer Networks by Tanenbaum",
        book_category: "Academic",
        book_price: 530,
        image1_path: "https://m.media-amazon.com/images/I/71pIJGRBg7L._AC_UF1000,1000_QL80_.jpg",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRZb5QyVFd4DfWBUTpn5j8xXbRoqHMBzGjhQ&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb9G9M3Ama43ZKPmj3i7o6n-hkoVmGXRGwzRSubSxBWghWs_1l4Fa1IdXbLJTglB8xWtw&usqp=CAU",
        image4_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0n66LhUH-d6Uy3KY52WB9Mm5AgOnkeqF1qw&s",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAThmA1OIiXqIZeMhZKPKkkCfXjDT4-Xeekc4EErJ04qX2OQ8kwXwmsP50n6Af17ArMbc&usqp=CAU"
    },
    //fiction books data
    {
        seller_name: "John",
        seller_contact: 9876543210,
        seller_city: "Mumbai",
        book_name: "The Alchemist by Paulo Coelho",
        book_category: "Fiction",
        book_price: 400,
        image1_path: "https://m.media-amazon.com/images/I/61HAE8zahLL.jpg",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcRPJrqHp8LMznRNaYkTPVP8A3c9IHoG3Iig&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQMA4rlzbYFZWRR7YuvYIl3q836AH49mBz4g&s",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg_K6O2YGrurguXf_AUfxxshw1_08-ekhhNJfKl8dME4Mx7dYQFvRKE5pz5N6apAsE4uM&usqp=CAU",
        image5_path:"https://5.imimg.com/data5/SELLER/Default/2024/3/398402678/LI/WZ/XP/125624699/the-alchemist-book-500x500.jpg"
    
    },
    {
        seller_name: "Samantha",
        seller_contact: 8765432109,
        seller_city: "Delhi",
        book_name: "1984 by George Orwell",
        book_category: "Fiction",
        book_price: 350,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkMawPGWXkqh40s2hE9JrTZfMdx4jWE5YDLw&s",
        image2_path: "https://m.media-amazon.com/images/I/81Wu8NC+bfL._AC_UF350,350_QL80_.jpg",
        image3_path: "https://c8.alamy.com/comp/2AXBDE0/nineteen-eighty-four-1984-a-dystopian-novel-by-george-orwell-paperback-book-2AXBDE0.jpg",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLupjXtmDnUtzvYI8HQoHMWFO9XgCbMoh1qA&s",
        image5_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNRhhgMe0ZVpJFDT6PhMD9aiOk4hwYSaxZVcuteE1oqZiE3pQMIre20HFRPOPYM73TO4o&usqp=CAU",
    },
    {
        seller_name: "Ravi",
        seller_contact: 9876123456,
        seller_city: "Bangalore",
        book_name: "The Catcher in the Rye by J.D. Salinger",
        book_category: "Fiction",
        book_price: 500,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcKbLoG01sx1LqNYQjsB5mNwZVPjN71J5i6w&s",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoMm4TH36G6zHJFsvfKbvDmyqnf9jBdOuGDw&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRanuztTL-77sNIEMEC6qgy6Yow5nRD1MrFeA&s",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCSiIwYv6q6dbUMiv9gA9at4BhCheDlRixAxMvDtdQ71lc4e6CDaPCBtNKhUjN-1Y92uE&usqp=CAU",
        image5_path:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZwYkSjKaznjoCqyid02pdHOghWEbxBanwAg&s"
    },
    {
        seller_name: "Ananya",
        seller_contact: 9998887770,
        seller_city: "Chennai",
        book_name: "Brave New World by Aldous Huxley",
        book_category: "Fiction",
        book_price: 450,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkSor7LOFTupY3jAzgRqIDSMK8xQJT3y1VOA&s",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3DRYWYPsthnfhalSLvUXsg-L-CcocDu438Q&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVqxr5VR4BzuSPam-EvQ2N5hnyZpvx3-Vye0pm7KqRI8C6i8rXc-HQV7plHP-cG-1feTY&usqp=CAU",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7msNj-PSBVAOcYSkyXaAjCQUAJFerywCkPL1BM1aaFr1oPVYtOwTzQzrXRaA11j-12dA&usqp=CAU"
    },
    //non fiction books
    {
        seller_name: "Riya",
        seller_contact: 9876543211,
        seller_city: "Mumbai",
        book_name: "Sapiens: A Brief History of Humankind",
        book_category: "Non-Fiction",
        book_price: 350,
        image1_path: "https://images.meesho.com/images/products/353384321/us5iw_512.webp",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Q7osKVxlku9VbmZBsXnba9eV0FRr5RNzLA&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7KJpe-jwWbjvoosMOfsCGkPUb6e5ewkcLVA&s",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSxQ8DCC-exOT4t9tfBDv_TyhHFYLDN4Ytr9nFhV5_rmFfmV6HJoWxbvqZl7ZWwMabm-c&usqp=CAU",
        image5_path: "https://online.pubhtml5.com/aouj/nahp/files/large/16.jpg"
    },
    {
        seller_name: "Karan",
        seller_contact: 9876543212,
        seller_city: "Delhi",
        book_name: "Atomic Habits",
        book_category: "Non-Fiction",
        book_price: 400,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDfszLlaz8_Qe13zgVWiubSYLLboxIxRdafg&s",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcY2nj-jqMmPvhY2UnUwQYql8xo5-Rx1vLy35FMzxu2FKjzr6QxoiI1CrKL9V_AvMLg4M&usqp=CAU",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcQOzTZsUS0U9auH-tfXH9o5HcAuVS_SjBt_lR1LlD3afjA7xqH8lmv8LtEOhW3D4TaFQ&usqp=CAU",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpfY5_d7pqFiCQ8KTzguyU8lEgp4YeMddnjnREVhrTrbpeJb0xvv7vKSlICe5YR2pW2r0&usqp=CAU",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJkEUQGljqYC68_1wY3DTxDnWDDiieAKWiLSPaCtvnl6SHnFkzf0w27_aKiz-JPpIllfQ&usqp=CAU"
    },
    {
        seller_name: "Meera",
        seller_contact: 9876543213,
        seller_city: "Bangalore",
        book_name: "The Power of Habit",
        book_category: "Non-Fiction",
        book_price: 300,
        image1_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCMkweTIfAwLpvzTwSPYHsNKxF4sp309A_uQ&s",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJx",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdNybKFjWF7sY8V7XNXBE187axe89AgojrPg&s",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDZ-hca_zHo_hMG14RiP7atVL8r-tYehgu53xoUsfXt95idQCGc1uqVkpTw_DCvFK7Ffs&usqp=CAU",
        image5_path: "https://insight.randomhouse.com/fullpage.do?pContentType=JPG&pName=fullpage&pISBN=9780812981605&pPageID=83"
    },
    {
        seller_name: "Arjun",
        seller_contact: 9876543214,
        seller_city: "Chennai",
        book_name: "Thinking, Fast and Slow",
        book_category: "Non-Fiction",
        book_price: 450,
        image1_path: "https://m.media-amazon.com/images/I/71f6DceqZAL._AC_UF1000,1000_QL80_.jpg",
        image2_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS25jegBNzAh0F3J6nPyMQBKokp61yc0IDlVg&s",
        image3_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9Nefj_FVXEN7TAKp_jWt0bjHZ6p_84Idl6qna4frPFAIIujsrz3tWK0mBsGeBWhxQkUo&usqp=CAU",
        image4_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD-K1IOWu70Q6mofteqEPb-1OPRODz2gvtXtwN6trVbMdETk58HFShtRsPDeGNH120-D4&usqp=CAU",
        image5_path: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRMUhzKhaQ3tHe8epaSZd3hPCjEdsD72k8blXs0Hyn8Fqe1u6MzdfaDqrqyP98_SXG3RA&usqp=CAU"
    }
    
]
module.exports = {data:samplelisting}